services:
  # This is the name of our development service
  dev:
    build:
      context: . # Use the current directory as the build context
      dockerfile: gem5-dev.Dockerfile # Tell it to use our specific Dockerfile

    image: gem5-dev:latest

    # These volumes are persistent and live on your host, managed by Docker
# These volumes are persistent and live on your host, managed by Docker
    volumes:
      # 1. Use named volumes for the source code
      - gem5-source:/workspace/gem5-tracer
      - garnet-visualizer-source:/workspace/garnet-web-visualizer

      # 2. A persistent volume for your gem5 build cache
      - gem5-ccache:/root/.cache/ccache

    # Keep the container running in the background
    command: sleep infinity

    # Set a consistent container name
    container_name: ors-dev-container

# This defines the named volumes, so they persist
volumes:
  gem5-ccache:
  gem5-source:
  garnet-visualizer-source:

