services:
  # This is the name of our development service
  dev:
    build:
      context: . # Use the current directory as the build context
      dockerfile: gem5-dev.Dockerfile # Tell it to use our specific Dockerfile

    # The image name is built from the .env file (e.g., ors-dev:latest)
    image: ${IMAGE_TAG}

    # These volumes are persistent and live on your host, managed by Docker
    volumes:
      # 1. A persistent volume for all your source code
      - ors-workspace:/workspace:cached

      # 2. A persistent volume for your gem5 build cache
      - gem5-ccache:/root/.cache/ccache

    # Keep the container running in the background
    command: sleep infinity

    # Set a consistent container name
    container_name: ors-dev-container

# This defines the named volumes, so they persist
volumes:
  gem5-ccache:
  ors-workspace:

